disabled_rules:
  - identifier_name
  - line_length
  - cyclomatic_complexity
  - redundant_discardable_let

type_body_length:
  warning: 250
  error: 400

function_body_length:
  warning: 80
  error: 120

file_length:
  warning: 600
  error: 1000

large_tuple:
  warning: 3
  error: 4
