disabled_rules:
  - cyclomatic_complexity
  - redundant_discardable_let
  - identifier_name

type_body_length:
  warning: 250
  error: 400

function_body_length:
  warning: 80
  error: 120

file_length:
  warning: 600
  error: 1000

line_length:
  ignores_comments: true

identifier_name:
  excluded:
    - id
